development:
  develop: false        # 是否开启开发模式（调试模式）
  
service:
  port: 9000
  
log:
  max_size: 50         # 日志文件最大 MB 数
  max_backups: 7       # 日志文件最多保留几个备份
  max_age: 30          # 日志文件最多保存多少天
  compress: true       # 是否启用压缩
  
mysql:
  # host: 127.123.2.1
  host: localhost
  port: 3306
  user: root
  password: 11111111
  database: fox
  # 设置最大空闲连接
  MaxIdleCons: 10
  # 设置最大打开连接
  MaxOpenCons: 100

redis:
  # host:
  host: 127.0.0.1
  port: 6379
  db: 0
  expires: 24
  
login:
  timeout: 120
  
ticker:
  # 默认刷新时间
  Second: 20
  
jwt:
  secret: "qiutianhong324"   # 用于签名的密钥，请设置一个足够强的随机字符串
  issuer: "Akita"                   # 签发者
  expires_in: 7                  # Token 过期时间（7天）
  leeway: 5s                        # 时间误差（允许误差5秒）
  access_token_expires_in: 12    # Access Token 过期时间（小时）
  refresh_token_expires_in: 168  # Refresh Token 过期时间（小时，7天）

file_storage:
  enabled: true # 是否启用文件存储
  type: local # 文件存储类型
  max_file_size: 10MB # 文件大小限制
  allowed_file_types: # 允许的文件类型
    - jpg
    - png 
    - pdf
  encryption: false # 是否启用文件加密
  local:
    path: ./uploads # 文件存储路径
    backup_path: ./backups # 文件备份路径
    permissions: 755 # 文件权限
  minio:
    endpoint: 114.55.131.151:9090 # 端点
    access_key: yugadmin # 访问密钥
    secret_key: 11111111 # 秘密密钥
    bucket: yugfos # 存储桶名称
    region: us-east-1 # 区域
    use_ssl: false # 是否使用 SSL
    bucket_policy: private # 文件存储策略
